AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  mykeypair:
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroupIp:
    Type: String
    Default: 0.0.0.0/0
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - m1.small
    - m1.large
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ea832bf7873542df
      InstanceType: !Ref InstanceTypeParameter
      KeyName: oregon-keypare
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          VolumeType: "gp3"
          DeleteOnTermination: true
          VolumeSize: 20
      SecurityGroups:
      - !Ref ServerSecurityGroup1
      - !Ref ServerSecurityGroup2

  ServerSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 192.168.1.1/32

  ServerSecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 192.168.1.1/32
